### ISSUE TITLE
can't get koala icons

### ISSUE THREAD

**Issue by diomed** [foooomio/view-background-image#13]
## Page URL

https://au.koala.com

## Image URL

koala icons

### OS

 Windows, 10

### Chrome Version

Vivaldi 1.16.1230.3

### Extension Version

2.6.0

**Comment by foooomio** [comment]
Since v2.7.0, SVG images have been experimentally supported. Please check it out.

I'm aware that it doesn't work well in some cases, but it'll be okay in most cases. I'll fix it in the future versions. If any problem, please file another issue.
