### ISSUE TITLE
problem in user icon in google docs documents 

### ISSUE THREAD

**Issue by shraga100** [foooomio/view-background-image#15]
https://docs.google.com/document/d/*/edit
The problem exists in the Google Docs documents

chrome version -74.0.3729.157
extension version 2.8.0
windows os
![2019-05-17 15_17_35-](https://user-images.githubusercontent.com/26792728/57927580-1d73fe00-78b7-11e9-801e-2e671b10e1b1.png)

**Comment by foooomio** [comment]
Thanks for your report. I'll try to fix it.

**Comment by foooomio** [comment]
Fixed in 9411f901109f649aafdaa4e53080e6d19a3495b4 and released as v2.8.1.
