### ISSUE TITLE
doesn't read background image, routed back to chrome web store page

### ISSUE THREAD

**Issue by bearpack8** [foooomio/view-background-image#21]
## Page URL

https://www.geocaching.com/geocache/GC446A7

## Image URL

background image which is red with runic type font

### OS

Windows 10

### Chrome Version

most current version based on steps followed to get the answer

### Extension Version

2.9.0

I added the chrome extension to view background images, but it's not working. I have reloaded the pages. I've closed chrome and reopened it. I've uninstalled the extension and reinstalled it. I have changed the extension settings. I have restarted my computer. All software versions are current. I have tried everything I can think of and it doesn't work.

**Comment by foooomio** [comment]
Thank you for reporting.

Is this the background image you want to view?
https://imgproxy.geocaching.com/27fdcf36e3c9b6b1f465cc4fadc0c429cd1904db?url=https%3A%2F%2Flh4.googleusercontent.com%2F-QFsDF9i_laU%2FUPDDTFu5D1I%2FAAAAAAAADso%2F6Pxu4nSgJlM%2Fs646%2Frunes.png

Unfortunately, it works in my environment and I have no idea why it doesn't work in your environment. Is there any error log of the extension output to the console?

**Comment by foooomio** [comment]
Perhaps you pressed the button on the toolbar. Not so, select the item in the right-click menu.

**Comment by bearpack8** [comment]
Yes, that is the background I was looking for.

I don't get an error message. I am right-clicking and using that option .
Below is the message pop up I receive.
[image: image.png]

I just did it again, and it worked this time. Hopefully it will continue to
do so.

Thank you for your help.

**Comment by bearpack8** [comment]
Yet, it's not working for this one. You can clearly see there is a
background image.
[image: image.png]

**Comment by foooomio** [comment]
I'm afraid that the images you posted are not displayed.

**Comment by foooomio** [comment]
I'm closing the issue because there is no reply.
