### ISSUE TITLE
Open background tab with middle click or manually set combination

### ISSUE THREAD

**Issue by maxoku** [foooomio/view-background-image#22]
It would be nice to open image(s) in background tab(s) (not switch automatically to the first one) with middle mouse button or maybe even by choosing any button or combination (e.g. ctrl+left click).

**Comment by foooomio** [comment]
Sounds good.

I found out that the feature can be implemented only on Firefox. Unfortunately it doesn't work on Chrome, but I'll try to implement it.

**Comment by foooomio** [comment]
Implemented in https://github.com/foooomio/view-background-image/commit/d1eb45875add68ff921ea9a8f9cab5462e392359 and released in v2.10.0.

**Comment by maxoku** [comment]
Perfect, thanks for adding it.
