### ISSUE TITLE
Doesn't work after restart

### ISSUE THREAD

**Issue by maxoku** [foooomio/view-background-image#23]
It works fine after installing (without permiting the private browsing), but it doesn't work after restarting the browser or disabling and enabling the add-on. Every time I just need to install it again from the file to make it work.

Windows 8.1
Waterfox Current (based on Firefox 68)
Add-on version: 2.9.0

**Comment by foooomio** [comment]
Thank you for reporting.

I reproduce this strange behavior on Firefox. I need to do some research.

**Comment by foooomio** [comment]
On Firefox, it seems that `chrome.runtime.onInstalled` won't be fired when the addon turns enabled.

I think this is a bug of Firefox... but I'll fix it in the next version.

**Comment by foooomio** [comment]
Fixed in https://github.com/foooomio/view-background-image/commit/8f6d5a787e25f00b3215671ba150e1a93fd00c3f and released in v2.10.0.

**Comment by maxoku** [comment]
It works, thanks for fixing.
