### ISSUE TITLE
Fail to get this background image

### ISSUE THREAD

**Issue by vuatintac** [foooomio/view-background-image#25]
## Page URL

https://detail.1688.com/pic/593272952875.html?spm=a261y.7663282.1998411378.1.17fe67c4MXE0aS

## Image URL

https://cbu01.alicdn.com/img/ibank/2019/140/949/11002949041_684257393.jpg

### OS

Windows 10 64bit

### Chrome Version

Version 85.0.4183.83 (Official Build) (64-bit)

### Extension Version

2.10.0

Thank you for your Extension.

**Comment by foooomio** [comment]
Thank you for the report, but the image on the page can be obtained without any problem in my environment. The image is displayed on the second tab of the opening two tabs.

**Comment by blakeperdue** [comment]
I agree it worked fine for me as well. 2 tabs, main image in the second tab.

**Comment by foooomio** [comment]
I'm closing the issue because there is no reply.
