### ISSUE TITLE
Stopped working in Firefox 102.4.0esr

### ISSUE THREAD

**Issue by tkzv** [foooomio/view-background-image#33]
After the auto-update the extension disappeared from context menu.

## Page URL

Everywhere, including https://www.google.com

## Image URL

https://www.google.com/images/searchbox/desktop_searchbox_sprites318_hr.webp
https://ssl.gstatic.com/gb/images/p1_d9c8f691.png

### OS

Gentoo Linux

### Chrome Version

Firefox 102.4.0esr (www-client/firefox-102.4.0:esr)

### Extension Version

2.10.3 from 2022-11-07

**Comment by foooomio** [comment]
Use latest Firefox

**Comment by tkzv** [comment]
Not an option, it's too buggy. That's what ESR is for.
