### ISSUE TITLE
Recover feature to open images in foreground tab

### ISSUE THREAD

**Issue by hrcspkla** [foooomio/view-background-image#37]
### OS
Win10 22H2
### Firefox Version
121.0.1
### Extension Version
2.10.4

Before the 2.10.2 version, users could open images in foreground tab with left click or in background tab with middle click, but current latest version always open in background. I attempted to install the older versions and more preferred them. Could you update plugin to support classic features?

**Comment by foooomio** [comment]
Read my comment on #31
