### ISSUE TITLE
[Feature Request]: Change background color

### ISSUE THREAD

**Issue by LatinSuD** [foooomio/view-background-image#43]
### Description

Please allow to change background color when displaying an image.
Some images don't work well with black background.

**Comment by foooomio** [comment]
I've released v3.0.4 that makes black images easier to see.

**Comment by LatinSuD** [comment]
Hi again. I found some specific test cases that challenge most viewing solutions, including the new one.

I also proposed a different solution based on animated waves. It may look a little weird, but it does the job.

You can see the test cases and my proposal here:
https://latinsud.com/kkd/view-background-image/view-background-image.html
