### ISSUE TITLE
I know you’ll just close this but I have to say it anyway: you have absolutely destroyed this add-on.

### ISSUE THREAD

**Issue by CT-ABT** [foooomio/view-background-image#47]
The only reason for this add-on to exist is its simplicity, otherwise people can just press F12 and find the background image themselves. There is absolutely no need for an extra page showing those extra texts and asking for review. This extra step, for whatever reason you have laid out, destroys the simplicity of this add-on and therefore makes it useless. (Even if your points were reasonable, you should try to bypass those limitations and keep the simplicity of this add-on, rather than adding that black page with extra texts.) You know people hate those things and yet you still choose to add that, thus uninstalling would be the final fate of this add-on. I have used this add-on for many years, and for this, I appreciate your hard work, unreservedly. But now, it’s time to say goodbye.

**Comment by CT-ABT** [comment]
And by reading other issues raised I saw you suggesting adding more functions to this add-on. My last word on this is: **this is totally wrong**. This add-on should stick to its simplicity, nothing else. If people want to, for instance, find the original image, read exif info of the image, rotate the image, bulk download the images, etc, they could use other add-ons (for example, Image Max URL, Exif Viewer, PhotoShow, or DownThemAll!, etc), adding that extra black page have already broken the simplicity of this add-on, adding more functions would be disastrous.

**Comment by foooomio** [comment]
duplicated #41

**Comment by foooomio** [comment]
Statistics show no change in the number of users. Only a few people are complaining.
